analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs
    - sort_constructors_first
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_declare_return_types
    - type_annotate_public_apis
    - unawaited_futures
    - use_super_parameters
